### ISSUE TITLE
Warning: Circular dependency detected

### ISSUE THREAD

**Issue by MatteoTrapasso** [jucasoft/ngrx-entity-crud-prime-ng-boilerplate#3]
in 'src\app\root-store\slide-menu-store\state.ts' sostituire:
import {SlideMenuStoreActions} from '@root-store/slide-menu-store/index';
con:
import * as SlideMenuStoreActions from '@root-store/slide-menu-store/actions';

**Comment by jucasoft** [comment]
soluzione corretta
